import { createSlice, PayloadAction } from '@reduxjs/toolkit';

export interface CounterState {
    value: number;
    status: String;
}

const initialState: CounterState = {
    value: 1,
    status: 'Active',
};

export const authSlice = createSlice({
    name: 'authentication',
    initialState,
    reducers: {
        incrementByAmount: (state, action: PayloadAction<number>) => {
            state.value += action.payload;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: () => {
    },
});

export const { incrementByAmount } = authSlice.actions;  //export actions
export default authSlice.reducer; //xport reducer
